# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 23:56
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170107_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=markdownx.models.MarkdownxField(default='Hello'),
            preserve_default=False,
        ),
    ]
