# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body2',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Matt McGovern', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='Testing', max_length=100),
            preserve_default=False,
        ),
    ]
